### ISSUE TITLE
Adds Support to StopMarketOrder

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean.Brokerages.Binance#7]
#### Expected Behavior
Supports `StopMarketOrder`.

#### Actual Behavior
In Lean we have the following message explaining why this implementation doesn't support `StopMarketOrder`:
Despite Binance API allows you to post STOP_LOSS and TAKE_PROFIT order types, they always fail with the content
`{"code":-1013,"msg":"Take profit orders are not supported for this symbol."}`

#### Potential Solution
N/A. Investigate whether this is still the case and why.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment]
We should add support to all types that Lean and Binance have in common.

**Comment by fishstoryyy** [comment]
Can I ask if there is an update on this? Agree with what Alex said in the issue description: Binance Futures API does support the following order types (see [here](https://binance-docs.github.io/apidocs/futures/en/#new-order-trade)):

LIMIT
MARKET
STOP
STOP_MARKET
TAKE_PROFIT
TAKE_PROFIT_MARKET
TRAILING_STOP_MARKET

I believe all of which are supported in Lean. Thanks.

**Comment by Romazes** [comment]
The screenshot links:
- https://developers.binance.com/docs/binance-spot-api-docs/rest-api/public-api-endpoints#new-order-trade
- https://developers.binance.com/docs/derivatives/usds-margined-futures/trade/rest-api

![image](https://github.com/user-attachments/assets/5118144a-1a95-4c36-bb95-0b52451c38af)
